### PR TITLE
database no new concepts

### PR DESCRIPTION
**Pull request by StasReichert**

### CODE REVIEW

**Comment by StasReichert** [comment]
@LinguList @LanguageStructure

This pull request has several slight deviations from our usual routine:
- since we cannot let the lexibank script "ignore" the new concepts when downloading data from Edictor, we first ran the script and then manually eliminated all of the new concepts from the .tsv file. Afterwards, the makecldf script was run as always, but on this manually edited database.
- for various reasons we cannot yet provide BibTeX entries for two newly added doculects. Therefore we made the lexibank script ignore the missing BibTeX and not print it into the errors.md file (but instead as warnings on the command line).
Otherwise we believe we have followed all of the usual steps while preparing a release.

**Comment by LanguageStructure** [comment]
There are no sources for the two proto-languages. The reconstructions will
consist of our own work.

**Comment by LinguList** [comment]
The script actually already only converts those entries which have a valid concepticon concept, as far as I know. And doing something manual is a generally bad idea.

**Comment by LanguageStructure** [comment]
should we include the concepts that we added after the blog post? They all
have a concepticon concept/ID.

**Comment by LinguList** [comment]
No.

**Comment by StasReichert** [comment]
Yes, the script does everything perfectly and it is indeed not a good idea to manually tweak it (we did it reluctantly), but the issue in this case, as far as I understood, is that there are about 250 concepts (currently partially filled out on Edictor) more than in the blog list and that these new additions are not supposed to be released just yet (so they are not on our Google Sheet among the established ones). They are all valid concepts with corresponding ConcepticonIDs, of course. But since lexibank downloads the whole database and runs the checks on it, these additional concepts result in an unwanted error list, which is why we decided to make the manual changes. So there is nothing wrong with the scripts. We just tried to exclude these new entries from the release version.

**Comment by LinguList** [comment]
Doing things manually at this stage is always problematic. We have an automated workflow to avoid this kind of problem. Also, note that your PR shows 451 concepts in contrast to 447 which we had before, so something is again at odds here, and we will have to find out now, which 4 concepts are somehow still passing, although they should not be there.

**Comment by LinguList** [comment]
I would suggest that we close this PR and I modify things in such a way that we don't need to do anything manually?

**Comment by LanguageStructure** [comment]
Yes, I agree.

**Comment by StasReichert** [comment]
That would definitely resolve the issue with new concepts as we cannot filter them out from Edictor. We ourselves are much in favour of standardized (and reproducible) workflows and are very grateful for your help with making our work with the database easier.

**Comment by LinguList** [comment]
We can filter concepts in edictor in the command we use to download the data.

**Pull request closed without merging**
