### PR TITLE
Fabricio

### PR DESCRIPTION
**Pull request by LanguageStructure**

### CODE REVIEW

**Comment by xrotwang** [comment]
Hm. That has not really worked, has it, see https://github.com/tupian-language-resources/tuled/blob/master/raw/tuled.tsv?
Also: Why did you already merge the PR? I thought we'd review it first and check the diff.
And don't you have a clone of the repos so that you can interact with it using git? It looks like you only used the GitHub web interface. When done via git, locally, you'd just have the ew file copied over `raw/tuled.tsv` and then commited and pushed.

**Comment by LanguageStructure** [comment]
Sorry! I think i misunderstood what I was supposed to do!
What should I do now?

**Comment by xrotwang** [comment]
https://medium.com/@urna.hybesis/pull-request-workflow-with-git-6-steps-guide-3858e30b5fa4

**Comment by LanguageStructure** [comment]
I cannot go through it now. Can I send you the file per email?

**Comment by xrotwang** [comment]
> I cannot go through it now. Can I send you the file per email?

Hm. The point of the PR workflow is so that we don't need to send stuff around in emails. So you sending me the file would just mean I have to create the PR.

**Pull request merged**
